// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Jest             = require("bs-jest/lib/js/src/jest.js");
var $$String         = require("bs-platform/lib/js/string.js");
var PlutoRover$Pluto = require("../src/PlutoRover.js");

var board = PlutoRover$Pluto.createEmptyBoard(100, 100);

var plutoOne = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      0
    ], /* North */0, board);

var plutoOneRotated = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      0
    ], /* South */1, board);

var plutoOutOfBoard = PlutoRover$Pluto.createPluto(/* tuple */[
      1,
      99
    ], /* West */3, board);

var movesBasic = "F, F, F, F, R, R, F, F, F, F";

var movesComplicated = "F, L, F";

var movesFromExample = "F, F, R, F, F";

var plutoFromExample = PlutoRover$Pluto.createPluto(/* tuple */[
      2,
      2
    ], /* East */2, board);

var hundredF = $$String.make(100, /* "F" */70);

describe("combine rotation plus moving pluto tests", (function () {
        Jest.test("it correctly moves, rotates 180 degrees and goes back to the same place", (function () {
                return Jest.Expect[/* toEqual */12](plutoOneRotated, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesBasic, plutoOne)));
              }));
        Jest.test("it doesn't go off the board if start at origin and then goes straight and turns left", (function () {
                return Jest.Expect[/* toEqual */12](plutoOutOfBoard, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesComplicated, plutoOne)));
              }));
        Jest.test("it goes to the same place if moves 100 times forward", (function () {
                return Jest.Expect[/* toEqual */12](plutoOne, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(hundredF, plutoOne)));
              }));
        return Jest.test("it behaves as described in the example", (function () {
                      return Jest.Expect[/* toEqual */12](plutoFromExample, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesFromExample, plutoOne)));
                    }));
      }));

var movesHundred = hundredF;

exports.board            = board;
exports.plutoOne         = plutoOne;
exports.plutoOneRotated  = plutoOneRotated;
exports.plutoOutOfBoard  = plutoOutOfBoard;
exports.movesBasic       = movesBasic;
exports.movesComplicated = movesComplicated;
exports.movesFromExample = movesFromExample;
exports.plutoFromExample = plutoFromExample;
exports.hundredF         = hundredF;
exports.movesHundred     = movesHundred;
/* board Not a pure module */
