// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Jest             = require("bs-jest/lib/js/src/jest.js");
var PlutoRover$Pluto = require("../src/PlutoRover.js");

var board = PlutoRover$Pluto.createEmptyBoard(100, 100);

var plutoOne = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      0
    ], /* North */0, board);

var plutoOneMoved = PlutoRover$Pluto.createPluto(/* tuple */[
      4,
      0
    ], /* North */0, board);

var movesBasic = "F,F,F,F";

var moveReturn = "F,B,F,B";

describe("basic pluto tests", (function () {
        Jest.test("it parses string into correct types", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            /* F */0,
                            /* :: */[
                              /* B */1,
                              /* :: */[
                                /* NotValid */4,
                                /* :: */[
                                  /* F */0,
                                  /* :: */[
                                    /* B */1,
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](PlutoRover$Pluto.mapCommandToMove("FBAFB")));
              }));
        Jest.test("it moves correctly in a straigth line", (function () {
                return Jest.Expect[/* toEqual */12](plutoOneMoved, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesBasic, plutoOne)));
              }));
        return Jest.test("it goes back to the same place if going backward", (function () {
                      return Jest.Expect[/* toEqual */12](plutoOne, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(moveReturn, plutoOne)));
                    }));
      }));

exports.board         = board;
exports.plutoOne      = plutoOne;
exports.plutoOneMoved = plutoOneMoved;
exports.movesBasic    = movesBasic;
exports.moveReturn    = moveReturn;
/* board Not a pure module */
