// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Jest             = require("bs-jest/lib/js/src/jest.js");
var PlutoRover$Pluto = require("../src/PlutoRover.js");

var board = PlutoRover$Pluto.createOneObstacleInRowBoard(100, 100, 5);

var plutoOne = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      5
    ], /* North */0, board);

var movesBasic = "FFFFF";

var plutoMoved = PlutoRover$Pluto.createPluto(/* tuple */[
      4,
      5
    ], /* North */0, board);

describe("basic pluto tests", (function () {
        return Jest.test("it doesn't get through obstacle", (function () {
                      return Jest.Expect[/* toEqual */12](plutoMoved, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesBasic, plutoOne)));
                    }));
      }));

exports.board      = board;
exports.plutoOne   = plutoOne;
exports.movesBasic = movesBasic;
exports.plutoMoved = plutoMoved;
/* board Not a pure module */
