// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Jest             = require("bs-jest/lib/js/src/jest.js");
var PlutoRover$Pluto = require("../src/PlutoRover.js");

var board = PlutoRover$Pluto.createOneObstacleInRowBoard(10, 10, 5);

var plutoOne = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      0
    ], /* East */2, board);

var movesBasic = "FFFFFFFFFFFFFFFFF";

var plutoMoved = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      5
    ], /* East */2, board);

describe("basic obstacle pluto tests", (function () {
        return Jest.test("it doesn't get through obstacle", (function () {
                      return Jest.Expect[/* toEqual */12](/* record */[
                                  /* board */plutoMoved[/* board */0],
                                  /* position */plutoMoved[/* position */1],
                                  /* direction */plutoMoved[/* direction */2],
                                  /* status : Obstacle */1
                                ], Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesBasic, plutoOne)));
                    }));
      }));

exports.board      = board;
exports.plutoOne   = plutoOne;
exports.movesBasic = movesBasic;
exports.plutoMoved = plutoMoved;
/* board Not a pure module */
