// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Jest             = require("bs-jest/lib/js/src/jest.js");
var PlutoRover$Pluto = require("../src/PlutoRover.js");

var board = PlutoRover$Pluto.createEmptyBoard(100, 100);

var plutoOne = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      0
    ], /* North */0, board);

var plutoRotated = PlutoRover$Pluto.createPluto(/* tuple */[
      0,
      0
    ], /* South */1, board);

var movesBasic = "R, R";

var moveReturn = "R,L,R,L";

describe("basic rotation pluto tests", (function () {
        Jest.test("it rotates correctly without moving", (function () {
                return Jest.Expect[/* toEqual */12](plutoRotated, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(movesBasic, plutoOne)));
              }));
        return Jest.test("it goes back to the same place if rotating", (function () {
                      return Jest.Expect[/* toEqual */12](plutoOne, Jest.Expect[/* expect */0](PlutoRover$Pluto.evaluateMoves(moveReturn, plutoOne)));
                    }));
      }));

exports.board        = board;
exports.plutoOne     = plutoOne;
exports.plutoRotated = plutoRotated;
exports.movesBasic   = movesBasic;
exports.moveReturn   = moveReturn;
/* board Not a pure module */
