// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var $$String    = require("bs-platform/lib/js/string.js");
var Caml_array  = require("bs-platform/lib/js/caml_array.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function mapCharToMove(c) {
  if (c !== 66) {
    if (c !== 70) {
      return /* NotValid */4;
    } else {
      return /* F */0;
    }
  } else {
    return /* B */1;
  }
}

function mapCommandToMove(command) {
  if (command === "") {
    return /* [] */0;
  } else {
    var length = command.length;
    var rest = $$String.sub(command, 1, length - 1 | 0);
    var tail = mapCommandToMove(rest);
    var firstCommand = mapCharToMove(Caml_string.get(command, 0));
    return /* :: */[
            firstCommand,
            tail
          ];
  }
}

function evaluateMove(pluto, m) {
  var position = pluto[/* position */1];
  var y = position[1];
  var x = position[0];
  var newPosition;
  switch (pluto[/* direction */2]) {
    case 0 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x + 1 | 0,
                y
              ]
          ) : /* tuple */[
            x - 1 | 0,
            y
          ];
        break;
    case 1 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x - 1 | 0,
                y
              ]
          ) : /* tuple */[
            x + 1 | 0,
            y
          ];
        break;
    case 2 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x,
                y + 1 | 0
              ]
          ) : /* tuple */[
            x,
            y - 1 | 0
          ];
        break;
    case 3 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x,
                y - 1 | 0
              ]
          ) : /* tuple */[
            x,
            y + 1 | 0
          ];
        break;
    
  }
  return /* record */[
          /* board */pluto[/* board */0],
          /* position */newPosition,
          /* direction */pluto[/* direction */2]
        ];
}

function evaluateMoves(moves, pluto) {
  var commands = mapCommandToMove(moves);
  return List.fold_left(evaluateMove, pluto, commands);
}

function createEmptyBoard(heigth, width) {
  var row = Caml_array.caml_make_vect(width, /* Empty */0);
  var listRow = $$Array.to_list(row);
  return $$Array.to_list(Caml_array.caml_make_vect(heigth, listRow));
}

function createPluto(startPosition, startDirection, board) {
  return /* record */[
          /* board */board,
          /* position */startPosition,
          /* direction */startDirection
        ];
}

exports.mapCharToMove    = mapCharToMove;
exports.mapCommandToMove = mapCommandToMove;
exports.evaluateMove     = evaluateMove;
exports.evaluateMoves    = evaluateMoves;
exports.createEmptyBoard = createEmptyBoard;
exports.createPluto      = createPluto;
/* No side effect */
