// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var $$String    = require("bs-platform/lib/js/string.js");
var Caml_array  = require("bs-platform/lib/js/caml_array.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function mapCharToMove(c) {
  var switcher = c - 66 | 0;
  if (switcher > 16 || switcher < 0) {
    return /* NotValid */4;
  } else {
    switch (switcher) {
      case 0 : 
          return /* B */1;
      case 4 : 
          return /* F */0;
      case 10 : 
          return /* L */3;
      case 1 : 
      case 2 : 
      case 3 : 
      case 5 : 
      case 6 : 
      case 7 : 
      case 8 : 
      case 9 : 
      case 11 : 
      case 12 : 
      case 13 : 
      case 14 : 
      case 15 : 
          return /* NotValid */4;
      case 16 : 
          return /* R */2;
      
    }
  }
}

function mapCommandToMove(command) {
  if (command === "") {
    return /* [] */0;
  } else {
    var length = command.length;
    var rest = $$String.sub(command, 1, length - 1 | 0);
    var tail = mapCommandToMove(rest);
    var firstCommand = mapCharToMove(Caml_string.get(command, 0));
    return /* :: */[
            firstCommand,
            tail
          ];
  }
}

function evaluateMove(pluto, m) {
  var position = pluto[/* position */1];
  var y = position[1];
  var x = position[0];
  var direction = pluto[/* direction */2];
  var newPosition;
  switch (direction) {
    case 0 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x + 1 | 0,
                y
              ]
          ) : /* tuple */[
            x - 1 | 0,
            y
          ];
        break;
    case 1 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x - 1 | 0,
                y
              ]
          ) : /* tuple */[
            x + 1 | 0,
            y
          ];
        break;
    case 2 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x,
                y + 1 | 0
              ]
          ) : /* tuple */[
            x,
            y - 1 | 0
          ];
        break;
    case 3 : 
        newPosition = m !== 1 ? (
            m !== 0 ? /* tuple */[
                x,
                y
              ] : /* tuple */[
                x,
                y - 1 | 0
              ]
          ) : /* tuple */[
            x,
            y + 1 | 0
          ];
        break;
    
  }
  var newDirection;
  switch (direction) {
    case 0 : 
        if (m >= 2) {
          switch (m - 2 | 0) {
            case 0 : 
                newDirection = /* East */2;
                break;
            case 1 : 
                newDirection = /* West */3;
                break;
            case 2 : 
                newDirection = direction;
                break;
            
          }
        } else {
          newDirection = direction;
        }
        break;
    case 1 : 
        if (m >= 2) {
          switch (m - 2 | 0) {
            case 0 : 
                newDirection = /* West */3;
                break;
            case 1 : 
                newDirection = /* East */2;
                break;
            case 2 : 
                newDirection = direction;
                break;
            
          }
        } else {
          newDirection = direction;
        }
        break;
    case 2 : 
        if (m >= 2) {
          switch (m - 2 | 0) {
            case 0 : 
                newDirection = /* South */1;
                break;
            case 1 : 
                newDirection = /* North */0;
                break;
            case 2 : 
                newDirection = direction;
                break;
            
          }
        } else {
          newDirection = direction;
        }
        break;
    case 3 : 
        if (m >= 2) {
          switch (m - 2 | 0) {
            case 0 : 
                newDirection = /* North */0;
                break;
            case 1 : 
                newDirection = /* South */1;
                break;
            case 2 : 
                newDirection = direction;
                break;
            
          }
        } else {
          newDirection = direction;
        }
        break;
    
  }
  return /* record */[
          /* board */pluto[/* board */0],
          /* position */newPosition,
          /* direction */newDirection
        ];
}

function evaluateMoves(moves, pluto) {
  var commands = mapCommandToMove(moves);
  return List.fold_left(evaluateMove, pluto, commands);
}

function createEmptyBoard(heigth, width) {
  var row = Caml_array.caml_make_vect(width, /* Empty */0);
  var listRow = $$Array.to_list(row);
  return $$Array.to_list(Caml_array.caml_make_vect(heigth, listRow));
}

function createPluto(startPosition, startDirection, board) {
  return /* record */[
          /* board */board,
          /* position */startPosition,
          /* direction */startDirection
        ];
}

exports.mapCharToMove    = mapCharToMove;
exports.mapCommandToMove = mapCommandToMove;
exports.evaluateMove     = evaluateMove;
exports.evaluateMoves    = evaluateMoves;
exports.createEmptyBoard = createEmptyBoard;
exports.createPluto      = createPluto;
/* No side effect */
